const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const optionModal=$('option-modal'),optionContent=$('option-content'),cartModal=$('cart-modal'),cartItems=$('cart-items'),cartTotal=$('cart-total'),cartCount=$('cart-count'),bottomCount=$('bottom-count'),bottomTotal=$('bottom-total'),franSummary=$('fran-summary'),customerName=$('customer-name'),placeOrderButton=$('place-order'),receiptCanvas=$('receipt-canvas');
const premiumExtras=['Ferrero Rocher','Gansito','Kinder Délice','Oreo','Chocolate Especial'];
const ingredients=[...customerCatalog.ingredientes.filter(x=>x!=='Chocolate Especial'),...premiumExtras];
const extraPrice=x=>premiumExtras.includes(x)?15:10;
const customCrepe={name:'Crepa a tu antojo',price:50,img:'Crepa Basica.png',type:'crepe',included:[]};
const crepes=[{name:'Crepa Nutella + Fresa',price:70,img:'Crepa Basica.png',type:'crepe',included:['Nutella','Fresa']},{name:'Crepa Nutella + Durazno',price:70,img:'Crepa Basica.png',type:'crepe',included:['Nutella','Durazno']},...customerCatalog.crepasEspeciales.filter(p=>p.activo).map((p,n)=>({...p,price:p.precio,type:'crepe',included:[...p.ingredientesBase,premiumExtras[n]]}))];
const frappes=[...customerCatalog.frappesBasicos,...customerCatalog.frappesPremium,...customerCatalog.frappesEspeciales].filter(p=>p.activo).map(p=>({...p,name:'Frappé '+p.name,price:p.med,type:'frappe',sizes:[['Mediano',p.med],['Grande',p.gde],['Jumbo',p.jumbo]]}));
const promos=[{name:'Capuchino 10 oz · 1 por $30',price:30,quantity:1,type:'frappe',img:'Capuchino.png'},{name:'Capuchino 10 oz · 2 por $50',price:50,quantity:2,type:'frappe',img:'Capuchino.png'}];
const others=[...customerCatalog.chamoyadas.filter(p=>p.activo).map(p=>({...p,name:'Chamoyada '+p.name,price:p.precio})),...customerCatalog.sodas.filter(p=>p.activo).map(p=>({...p,name:'Soda italiana '+p.name,price:p.precio})),{name:'Vaso Combo',price:150,img:'vaso Combo.png',type:'combo'},{name:'Sopa Maruchan',price:35,img:'Maruchan.png'}];
let cart=[],selectedProduct=null;
const cardProducts=[];
function cards(id,items){$(id).innerHTML=items.map(p=>{const n=cardProducts.push(p)-1;return `<button class="product neon bg-white rounded-3xl p-3 text-left" onclick="selectProduct(cardProducts[${n}])"><img src="${esc(p.img)}" alt="${esc(p.name)}" class="w-full h-28 object-contain"><h3 class="font-black leading-tight mt-2">${esc(p.name)}</h3><p class="text-pink-600 font-black text-lg">${p.sizes?'Desde ':''}$${p.price}</p><p class="text-xs">${p.sizes?p.sizes.map(([s,v])=>`${s} $${v}`).join(' · '):'Toca para personalizar'}</p></button>`}).join('')}
cards('popular-grid',[...crepes.slice(0,2),{...frappes.find(p=>p.name==='Frappé Ferrero Rocher'),defaultSize:'Grande'},{...frappes.find(p=>p.name==='Frappé Capuchino'),defaultSize:'Grande'}]);cards('frappe-grid',frappes);cards('crepe-grid',crepes);cards('other-grid',others);cards('promo-grid',promos);
function checkOption(value,checked,label,kind){return `<label class="pill flex items-center gap-2 p-3 rounded-xl"><input class="w-5 h-5" type="checkbox" data-kind="${kind}" value="${esc(value)}" ${checked?'checked':''} onchange="updateOptionPrice()">${esc(label)}</label>`}
function selectProduct(p){selectedProduct=p;let choices='';if(p.sizes)choices+=`<fieldset><legend class="font-bold mb-2">Elige tu tamaño</legend>${p.sizes.map(([s,v],n)=>`<label class="pill block p-3 rounded-xl mb-2"><input type="radio" name="size" value="${s}" ${(p.defaultSize?p.defaultSize===s:n===0)?'checked':''} onchange="updateOptionPrice()"> ${s} — $${v}</label>`).join('')}</fieldset>`;
if(p.type==='crepe')choices+=`<p class="font-bold mb-2">Precio base $${p.price}</p><p class="text-sm mb-3">Marca o desmarca ingredientes. ${p.included.length?'Los incluidos se pueden quitar sin cambiar el precio base. ':''}Cada ingrediente adicional cuesta $10; chocolates premium $15.</p><div class="grid grid-cols-1 sm:grid-cols-2 gap-2">${ingredients.map(x=>checkOption(x,p.included.includes(x),`${x} · ${p.included.includes(x)?'incluido':'+$'+extraPrice(x)}`,'ingredient')).join('')}</div>`;
if(p.type==='combo')choices+=`<p class="font-bold">Frutas y toppings incluidos · $150</p><div class="grid grid-cols-2 gap-2">${['Fresa','Plátano','Durazno','Nuez','Almendra','Chispas de chocolate'].map(x=>checkOption(x,false,x,'combo')).join('')}</div>`;
if(p.type==='frappe')for(let n=0;n<(p.quantity||1);n++)choices+=`<fieldset class="mt-4 p-3 rounded-xl bg-pink-50"><legend class="font-bold">${p.quantity===2?'Vaso '+(n+1):'Personaliza tu frappé'}</legend><label class="block">Crema batida<select id="cream-${n}" class="w-full p-3 rounded-xl"><option>Con crema batida</option><option>Sin crema batida</option></select></label><label class="block mt-2">Azúcar<select id="sugar-${n}" class="w-full p-3 rounded-xl"><option>Normal</option><option>Menos azúcar</option><option>Más azúcar</option></select></label><label class="block mt-2">Leche<select id="milk-${n}" class="w-full p-3 rounded-xl"><option>Entera</option><option>Deslactosada</option></select></label></fieldset>`;
optionContent.innerHTML=`<h2 class="text-2xl font-black">${esc(p.name)}</h2><img src="${esc(p.img)}" alt="" class="w-32 h-32 object-contain mx-auto"><div id="choice-area">${choices}</div><label for="product-note" class="block font-bold mt-4">Instrucciones especiales</label><textarea id="product-note" maxlength="240" rows="3" placeholder="Ej. fruta aparte, sin crema batida…" class="w-full border p-3 rounded-xl"></textarea><p id="option-price" aria-live="polite" class="font-black text-xl mt-3"></p><button onclick="confirmOptions()" class="w-full mt-3 bg-pink-500 text-white rounded-2xl py-4 font-black">Agregar al pedido</button>`;optionModal.classList.remove('hidden');optionModal.classList.add('flex');updateOptionPrice()}
function optionSelection(){const p=selectedProduct;let price=p.price,name=p.name,details=[];if(p.sizes){const size=document.querySelector('input[name=size]:checked').value;price=p.sizes.find(s=>s[0]===size)[1];name+=' ('+size+')'}if(p.type==='crepe'){const chosen=Array.from(document.querySelectorAll('[data-kind=ingredient]:checked'),i=>i.value);price+=chosen.filter(x=>!p.included.includes(x)).reduce((s,x)=>s+extraPrice(x),0);details.push('Ingredientes: '+(chosen.join(', ')||'sencilla'));const removed=p.included.filter(x=>!chosen.includes(x));if(removed.length)details.push('Sin: '+removed.join(', '))}if(p.type==='combo')details.push('Selección: '+(Array.from(document.querySelectorAll('[data-kind=combo]:checked'),i=>i.value).join(', ')||'sin frutas ni toppings'));if(p.type==='frappe')for(let n=0;n<(p.quantity||1);n++)details.push(`${p.quantity===2?'Vaso '+(n+1)+': ':''}${$('cream-'+n).value}; azúcar: ${$('sugar-'+n).value}; leche: ${$('milk-'+n).value}`);const note=$('product-note').value.trim();if(note)details.push('Nota: '+note);return {name,price,img:p.img,details,quantity:p.quantity||1}}
function updateOptionPrice(){$('option-price').textContent='Total: $'+optionSelection().price}
function confirmOptions(){addItem(optionSelection());closeOptions()}
function closeOptions(){optionModal.classList.add('hidden');optionModal.classList.remove('flex')}
function total(){return cart.reduce((s,i)=>s+i.price,0)}
function updateCart(){cartCount.textContent=bottomCount.textContent=cart.reduce((s,i)=>s+(i.quantity||1),0);bottomTotal.textContent=total()}
function addItem(i){cart.push(i);updateCart();franSummary.textContent=`¡Buena elección! Agregaste ${i.name}. ${i.details.join('. ')}. Tu pedido suma $${total()}.`}
function verCarrito(){cartItems.innerHTML=cart.length?cart.map((i,n)=>`<div class="pill rounded-xl p-3 flex gap-3"><img src="${esc(i.img)}" alt="" class="w-14 h-14 object-contain"><div class="flex-1"><b>${esc(i.name)}</b><p class="text-sm">${esc(i.details.join(' · '))}</p><strong>$${i.price}</strong></div><button aria-label="Quitar ${esc(i.name)}" onclick="removeItem(${n})" class="text-red-500 p-2">✕</button></div>`).join(''):'<p class="text-center py-5">Aún no agregas productos.</p>';cartTotal.textContent=total();cartModal.classList.remove('hidden');cartModal.classList.add('flex');updateCash()}
function removeItem(n){cart.splice(n,1);updateCart();verCarrito();franSummary.textContent=`Tu pedido suma $${total()}.`}
function closeCart(){cartModal.classList.add('hidden');cartModal.classList.remove('flex')}
function readCash(){const v=$('cash-option').value;return v==='exact'?total():v==='other'?Number($('cash-other').value):v?Number(v):NaN}
function updateCash(){const isCash=document.querySelector('input[name=payment]:checked').value==='Efectivo contra entrega';$('cash-fields').classList.toggle('hidden',!isCash);$('cash-other').classList.toggle('hidden',$('cash-option').value!=='other');const cash=readCash();$('cash-change').textContent=!Number.isFinite(cash)?'Prepararemos tu cambio con este dato.':cash<total()?'Ese monto no cubre el total.':'Tu cambio: $'+(cash-total()).toFixed(2)}
document.querySelectorAll('input[name=payment]').forEach(i=>i.addEventListener('change',updateCash));
function makeReceipt(o){const c=receiptCanvas,x=c.getContext('2d');c.width=1080;x.font='30px sans-serif';const lines=[];function wrap(text){let line='';for(const word of String(text).split(/\s+/)){if(x.measureText(line+' '+word).width>880){lines.push(line);line=word}else line+=(line?' ':'')+word}lines.push(line)}wrap('Folio: '+o.id);wrap('Cliente: '+o.cliente);o.items.forEach(i=>{wrap(i.name+' — $'+i.price);(i.details||[]).forEach(wrap);lines.push('')});wrap('TOTAL: $'+o.items.reduce((s,i)=>s+i.price,0));wrap('Pago: '+o.pago);if(o.efectivo!==null)wrap(`Efectivo: $${o.efectivo} · Cambio: $${o.cambio} ${o.denominacion}`);if(o.nota)wrap('Instrucciones: '+o.nota);wrap('Tiempo estimado: 20–40 minutos');wrap('Comprobante de pedido; no acredita el pago.');c.height=Math.max(1000,lines.length*46+350);x.fillStyle='#fff2f8';x.fillRect(0,0,c.width,c.height);x.fillStyle='#3d204b';x.font='bold 56px sans-serif';x.fillText('DULCE BOCADO',90,100);x.font='bold 34px sans-serif';x.fillText('COMPROBANTE DE PEDIDO',90,165);x.font='30px sans-serif';lines.forEach((l,n)=>x.fillText(l,90,250+n*46));x.fillStyle='#9b6cdf';x.fillText('@dulcebocadotlax',90,c.height-55);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download=`Dulce-Bocado-${o.id}.png`;a.click()}
