const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),Module=require('node:module'),esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');let version=0,failComplete=false;const maps=new Map();
function fakeStore({name}){if(!maps.has(name))maps.set(name,new Map());const m=maps.get(name);return {async get(k){return structuredClone(m.get(k)?.data||null)},async getWithMetadata(k){return structuredClone(m.get(k)||null)},async setJSON(k,data,opt={}){if(failComplete&&data.status==='done'){failComplete=false;throw Error('offline');}const old=m.get(k);if(opt.onlyIfNew&&old||opt.onlyIfMatch&&old?.etag!==opt.onlyIfMatch)return {modified:false};const etag=String(++version);m.set(k,{data:structuredClone(data),etag});return {modified:true,etag}},async delete(k){m.delete(k)},async list(){return {blobs:[...m.keys()].map(key=>({key}))}}}}
global.__fakeStore=fakeStore;global.__pushCount=0;const env={STAFF_PIN:'0000',STAFF_SESSION_SECRET:'test-session-secret-that-is-at-least-32-chars',VAPID_PUBLIC_KEY:'test',VAPID_PRIVATE_KEY:'test'};global.Netlify={env:{get:k=>env[k]}};
async function load(file){const result=await esbuild.build({entryPoints:[path.join(root,file)],bundle:true,platform:'node',format:'cjs',write:false,plugins:[{name:'test-services',setup(b){b.onResolve({filter:/^(@netlify\/blobs|web-push)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='web-push'?'export default {async sendNotification(){globalThis.__pushCount++}}':'export const getStore=globalThis.__fakeStore;export const getDeployStore=globalThis.__fakeStore;'}));}}]});const m=new Module(file,module);m.filename=path.join(root,file);m.paths=module.paths;m._compile(result.outputFiles[0].text,m.filename);return m.exports;}
(async()=>{
 const auth=(await load('netlify/functions/staff-session.mts')).default;
 const context={ip:'test-ip',deploy:{context:'production'}};const origin='https://example.test';const request=(path,body,method='POST',cookie)=>new Request(origin+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});
 assert.equal((await auth(request('/auth',null,'GET'),context)).status,200);
 assert.equal((await auth(request('/auth',{pin:'9999'}),context)).status,401);
 const login=await auth(request('/auth',{pin:'0000'}),context);assert.equal(login.status,200);const cookie=login.headers.get('set-cookie');assert(cookie.includes('HttpOnly')&&cookie.includes('Secure'));
 assert.equal((await (await auth(request('/auth',null,'GET',cookie),context)).json()).authenticated,true);
 assert.equal((await (await auth(request('/auth',null,'GET',cookie.replace('db_staff=','db_staff=x')),context)).json()).authenticated,false);
 for(let i=0;i<5;i++)assert.equal((await auth(request('/auth',{pin:'9999'}),context)).status,401);
 assert.equal((await auth(request('/auth',{pin:'0000'}),context)).status,429);
 assert.equal((await auth(new Request(origin+'/auth',{method:'POST',body:'{}'}),context)).status,403);
 const orderApi=(await load('netlify/functions/customer-order.mts')).default;let writes=0;const published=new Map();global.fetch=async(url,opt)=>{if(String(url).startsWith('https://firestore.googleapis.com')){const id=new URL(url).searchParams.get('documentId');if(published.has(id))return new Response('{}',{status:409});writes++;published.set(id,JSON.parse(opt.body));return new Response('{}',{status:200});}throw Error('Unexpected external request')};
 const input={id:'f8657b1e-ab37-416b-8533-777f43a876ec',cliente:'Test',items:[{price:1,selection:{product:'Crepa a tu antojo',ingredients:['Nutella','Ferrero Rocher'],note:'Fruta aparte'}}],pago:'Efectivo contra entrega',efectivo:100,nota:'Entregar en mostrador'};
 const responses=await Promise.all([orderApi(request('/order',input),context),orderApi(request('/order',input),context)]);assert(responses.some(r=>r.status===200));assert.equal([...maps.get('customer-orders').values()].filter(v=>v.data.status==='done').length,1);
 const replay=await (await orderApi(request('/order',input),context)).json();assert.equal(replay.duplicate,true);assert.equal(replay.order.total,75);assert.equal(replay.order.cambio,25);assert.equal([...maps.get('customer-orders').values()].filter(v=>v.data.status==='done').length,1);assert.equal(replay.order.items[0].precio,75);
 assert.equal((await orderApi(request('/order',{...input,cliente:'Other'}),context)).status,409);
 assert.equal((await orderApi(request('/order',{...input,id:crypto.randomUUID(),efectivo:10}),context)).status,400);
 const retryInput={...input,id:crypto.randomUUID()};failComplete=true;assert.equal((await orderApi(request('/order',retryInput),context)).status,503);assert.equal((await orderApi(request('/order',retryInput),context)).status,200);assert.equal([...maps.get('customer-orders').values()].filter(v=>v.data.status==='done').length,2);
 const staffOrders=(await load('netlify/functions/staff-orders.mts')).default;assert.equal((await staffOrders(request('/orders',null,'GET'),context)).status,401);const list=await (await staffOrders(request('/orders',null,'GET',cookie),context)).json();assert.equal(list.orders.length,2);const row=list.orders[0];const update=new Request(origin+'/orders?id='+row.id,{method:'PUT',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json','If-Match':row._version},body:JSON.stringify({...row,estado:'listo'})});assert.equal((await staffOrders(update,context)).status,200);const after=await (await orderApi(request('/order',input),context)).json();assert.equal(after.order.estado,'pendiente');assert.equal(maps.get('customer-orders').get(row.id).data.order.estado,'listo');
 const terminal=(await load('netlify/functions/terminal.mjs')).default;assert.equal((await terminal(request('/terminal',{amount:10}))).status,401);
 const push=(await load('netlify/functions/push-subscription.mts')).default;assert.equal((await push(request('/push',null,'GET'),context)).status,401);assert.equal((await push(request('/push',{endpoint:'http://127.0.0.1',keys:{}},'POST',cookie),context)).status,400);
 for(const file of ['admin.html','mesero.html','cocina.html'])for(const s of fs.readFileSync(path.join(root,file),'utf8').matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g))new vm.Script(s[1]);
 assert(!fs.readFileSync(path.join(root,'staff-auth.bundle.js'),'utf8').includes(env.STAFF_PIN));console.log('PASS: PIN session, cookie tampering, origin checks, attempt limit, protected terminal/push, concurrent order replay, immutable order contents, server pricing, failure/retry, staff syntax. All services mocked; no live orders or notifications.');
})().catch(e=>{console.error(e);process.exit(1)});
